name: Lore Origins - Auto-export Action

on:
  push:
    branches: [ main, wip ]
  pull_request:
    branches: [ main, wip ]

  workflow_dispatch:

jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - run: |
          haxe -version
          haxelib install --quiet hxnodejs
          haxelib setup ~/haxelib
      - name: Install hxcpp 4.3.2
        run: |
          haxelib install --quiet hxcpp 4.3.2
      - name: Install lime
        run: |
          haxelib install --quiet lime
      - name: Install openfl
        run: |
          haxelib install --quiet openfl
      - name: Install and Setup flixel 5.5.0
        run: |
          haxelib --quiet install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib run lime setup
      - name: Install flixel tools and others
        run: |
          haxelib install --quiet flixel-tools
          haxelib install --quiet flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install --quiet flixel-addons
      - name: Install tjson
        run: |
          haxelib install --quiet tjson 1.0.4
      - name: Install hscript-iris 1.0.2
        run: |
          haxelib install --quiet hscript-iris 1.0.2
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install --quiet hxCodec 3.0.2
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install --quiet hxvlc 2.2.1
      - name: Install other vital libraries
        run: |
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install --quiet hxdiscord_rpc 1.2.4
      - name: List Installed Haxelibs
        run: haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: 'export/release/linux/bin'
  windows-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - name: Install and Setup Haxelib
        run: |
          haxelib setup ~/haxelib
        shell: cmd
      - name: Install hxcpp
        run: |
          haxelib install --quiet hxcpp 4.3.2
        shell: cmd
      - name: Install lime
        run: |
          haxelib install --quiet lime
        shell: cmd
      - name: Install openfl
        run: |
          haxelib install --quiet openfl
        shell: cmd
      - name: Install and Setup flixel 5.5.0
        run: |
          haxelib --quiet install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib run lime setup
        shell: cmd
      - name: Install flixel tools and others
        run: |
          haxelib install --quiet flixel-tools
          haxelib install --quiet flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install --quiet flixel-addons
        shell: cmd
      - name: Install tjson
        run: |
          haxelib install --quiet tjson 1.0.4
        shell: cmd
      - name: Install hscript-iris 1.0.2
        run: |
          haxelib install --quiet hscript-iris 1.0.2
        shell: cmd
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install --quiet hxCodec 3.0.2
        shell: cmd
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install --quiet hxvlc 2.2.1
        shell: cmd
      - name: Install other vital libraries
        run: |
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install --quiet hxdiscord_rpc 1.2.4
        shell: cmd
      - name: List Installed Haxelibs
        run: haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: export/release/windows/bin
  mac-release:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - name: Install and Setup Haxelib
        run: |
          haxelib setup ~/haxelib
      - name: Install hxcpp
        run: |
          haxelib install --quiet hxcpp 4.3.2
      - name: Install lime
        run: |
          haxelib install --quiet lime
      - name: Install openfl
        run: |
          haxelib install --quiet openfl
      - name: Install and Setup flixel 5.5.0
        run: |
          haxelib --quiet install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib run lime setup
      - name: Install flixel tools and others
        run: |
          haxelib install --quiet flixel-tools
          haxelib install --quiet flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install --quiet flixel-addons
      - name: Install tjson
        run: |
          haxelib install --quiet tjson 1.0.4
      - name: Install hscript-iris 1.0.2
        run: |
          haxelib install --quiet hscript-iris 1.0.2
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install --quiet hxCodec 3.0.2
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install --quiet hxvlc 2.2.1
      - name: Install other vital libraries
        run: |
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install --quiet hxdiscord_rpc 1.2.4
      - name: List Installed Haxelibs
        run: haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-release
          path: export/release/macos/bin

  android-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install specific NDK version
        run: |
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;21.4.7075529"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: |
          haxe -version
          haxelib install --quiet hxnodejs
          haxelib setup ~/haxelib
      - name: Install hxcpp 4.3.2
        run: |
          haxelib install --quiet hxcpp 4.3.2
      - name: Install lime
        run: |
          haxelib install --quiet lime
      - name: Install openfl
        run: |
          haxelib install --quiet openfl
      - name: Install and Setup flixel 5.5.0
        run: |
          haxelib --quiet install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib run lime setup
      - name: Install flixel tools and others
        run: |
          haxelib install --quiet flixel-tools
          haxelib install --quiet flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install --quiet flixel-addons
      - name: Install tjson
        run: |
          haxelib install --quiet tjson 1.0.4
      - name: Install hscript-iris 1.0.2
        run: |
          haxelib install --quiet hscript-iris 1.0.2
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install --quiet hxCodec 3.0.2
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install --quiet hxvlc 2.2.1
      - name: Install other vital libraries
        run: |
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install --quiet hxdiscord_rpc 1.2.4
      - name: List Installed Haxelibs
        run: haxelib list

      - name: Setup Android paths for Lime
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libc6-dev-i386

          echo "Android SDK: $ANDROID_SDK_ROOT"
          echo "Android NDK: $ANDROID_NDK_ROOT" 
          echo "Java Home: $JAVA_HOME"

          printf '%s\n%s\n%s\n' "$ANDROID_SDK_ROOT" "$ANDROID_NDK_ROOT" "$JAVA_HOME" | haxelib run lime setup android

          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
      - name: Build Android APK
        run: |
          export ANDROID_NDK=$ANDROID_NDK_ROOT
          export NDK_ROOT=$ANDROID_NDK_ROOT

          haxelib run lime build android -release --app-version="4.0.0-${{ github.run_id }}"
      - name: Show APK Path
        run: find export/release/android -type f -name "*.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: export/release/android/bin/app/build/outputs/apk/debug/Lore Origins-debug.apk

  ios-release:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - name: Install and Setup Haxelib
        run: |
          haxelib setup ~/haxelib
      - name: Install hxcpp
        run: |
          haxelib install --quiet hxcpp 4.3.2
      - name: Install lime
        run: |
          haxelib install --quiet lime
      - name: Install openfl
        run: |
          haxelib install --quiet openfl
      - name: Install and Setup flixel 5.5.0
        run: |
          haxelib --quiet install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib run lime setup
      - name: Install flixel tools and others
        run: |
          haxelib install --quiet flixel-tools
          haxelib install --quiet flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install --quiet flixel-addons
      - name: Install tjson
        run: |
          haxelib install --quiet tjson 1.0.4
      - name: Install hscript-iris 1.0.2
        run: |
          haxelib install --quiet hscript-iris 1.0.2
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install --quiet hxCodec 3.0.2
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install --quiet hxvlc 2.2.1
      - name: Install other vital libraries
        run: |
          haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install --quiet hxdiscord_rpc 1.2.4
      - name: List Installed Haxelibs
        run: haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Build iOS project (unsigned)
        run: |
          haxelib run lime build ios --app-version="4.0.0-${{ github.run_id}}" -simulator
          haxelib run lime create ios --app-version="4.0.0-${{ github.run_id}}"
      - name: Upload iOS Project Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-project
          path: export/release/ios